### ISSUE TITLE
Error on FBUtil.cs

### ISSUE THREAD

**Issue by achouliarop** [fbsamples/friendsmash-unity#1]
Assets/Scripts/FBUtil.cs(48,30): error CS0103: The name `MiniJSON' does not exist in the current context

and many similar errors on this script

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by cmlewis89** [comment]
With the 2015 refresh, this issue is resolved.
