### ISSUE TITLE
Unity Canvas Payments Complete - Coin packages don't show up!!

### ISSUE THREAD

**Issue by ammaraud** [fbsamples/friendsmash-unity#11]
Okay so I have corrected the initial errors, namely:
1- 'Facebook' not found. Corrected by importing the latest facebook unity sdk.
2- Internal Compiler Error. Corrected the AppRequest params to not have names.

But i am still stuck, as the coin packages dont show up!!! I am using my own own App Id here. Can someone please help me out?

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by cmlewis89** [comment]
With the 2015 refresh, this issue is resolved.
