### ISSUE TITLE
Facebook Unity SDK

### ISSUE THREAD

**Issue by Narzerus** [fbsamples/friendsmash-unity#12]
When exporting to iOS it seems to only work the first time, the second one it corrupts the .plist file. Throwing:

'''
XmlException: 'dict' is expected'
'''

It actually has to do with a flawed generation of a </string> tag.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by cmlewis89** [comment]
With the 2015 refresh, this issue is resolved.
