### ISSUE TITLE
Does not contain a definition for `CelebFriend'

### ISSUE THREAD

**Issue by nabeelsaleem** [fbsamples/friendsmash-unity#15]
Assets/Scripts/MainMenu.cs(605,83): error CS0117: `GameStateManager' does not contain a definition for `CelebFriend'

@andyborrell ,  you forget to mention this...

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by cmlewis89** [comment]
With the 2015 refresh, this issue is resolved.
