### ISSUE TITLE
400 Bad Request invitable_friends

### ISSUE THREAD

**Issue by maujart** [fbsamples/friendsmash-unity#16]
Hi

The projects works but I get a 400 Bad Request because of this part  : 
,invitable_friends.limit(100).fields(first_name,id,picture.width(128).height(128))

on the  meQueryString initialisation.

Removing it, and keeping only :
//string meQueryString = "/v2.0/me?fields=id,first_name,friends.limit(100).fields(first_name,id,picture.width(128).height(128))";

works and I don t get any error 400 but I miss half of my friends.

How can I fix that ?

**Comment by animepauly** [comment]
Same issue as well. I logged a bug with Facebook, hopefully there will be some movement on this soon. If anyone has an answer I'm all ears :)

https://developers.facebook.com/bugs/411068479069082

**Comment by cmlewis89** [comment]
This has been resolved in the latest v7.0.1 and v7.0.2 Beta releases.
See: https://developers.facebook.com/bugs/1493972094150167/

Download the beta release here: https://developers.facebook.com/docs/unity/downloads#beta
