### ISSUE TITLE
The best overloaded method match for `FB.AppRequest(string, string[]

### ISSUE THREAD

**Issue by koljanich** [fbsamples/friendsmash-unity#18]
Hello! Unity 4.6.2f1 FB SDK Package 6.2.1 Friend Smash Project - friendsmash_payments_complete. Error in Unity: 
 The best overloaded method match for `FB.AppRequest(string, string[], System.Collections.Generic.List<object>, string[], int?, string, string, Facebook.FacebookDelegate)' has some invalid arguments

Source Error code:
 FB.AppRequest(
                message: "I just smashed you " + GameStateManager.Score.ToString() + " times! Can you beat it?",
                to: recipient,
                filters : "",
                excludeIds : null,
                maxRecipients : null,
                data: "{\"challenge_score\":" + GameStateManager.Score.ToString() + "}",
                title: "Friend Smash Challenge!",
                callback:appRequestCallback
                );

**Comment by nhatthuan** [comment]
FB.AppRequest("I just smashed you " + GameStateManager.Score.ToString() + " times! Can you beat it?", recipient, null, null, null, "{\"challenge_score\":" + GameStateManager.Score.ToString() + "}", "Friend Smash Challenge!", appRequestCallback);

It Worked For Me

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by cmlewis89** [comment]
With the 2015 refresh, this issue is resolved.
