### ISSUE TITLE
No overload for method `AppRequest' takes `6' arguments

### ISSUE THREAD

**Issue by dhanrajsinh24** [fbsamples/friendsmash-unity#19]
Assets/Scripts/MainMenu.cs(641,16): error CS1501: No overload for method `AppRequest' takes `6' arguments

in  this part :

FB.AppRequest(
                to: null,
                filters : "",
                excludeIds : null,
                message: "Friend Smash is smashing! Check it out.",
                title: "Play Friend Smash with me!",
                callback:appRequestCallback
                );

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by dhanrajsinh24** [comment]
Please update this project as it has old methods.

**Comment by cmlewis89** [comment]
With the 2015 refresh, this issue is resolved.

**Comment by dhanrajsinh24** [comment]
Thanks!
