### ISSUE TITLE
InvalidOperationException: Attempt to call Canvas interface on non canvas platform

### ISSUE THREAD

**Issue by cboxgo** [fbsamples/friendsmash-unity#21]
When running the Facebook Pay example (on Android,) that initiates FB.Canvas.Pay, it always returns this error.  Any idea why?  There's no indication that FB.Canvas.Pay is unsupported on Android in any of the Facebook documentation.

**Comment by cboxgo** [comment]
I just read that Google only allows their payments on Android and Apple only allows their payments on iOS, so I guess this is not really a bug...

**Comment by cmlewis89** [comment]
Thank you for surfacing this @cboxgo I will update the sample to only use FB payments on web.
