### ISSUE TITLE
Facebook Unity SDK...

### ISSUE THREAD

**Issue by Chisha14** [fbsamples/friendsmash-unity#22]
I am using Unity 5.0.2 with Facebook SDK v7.8.0 where everything is working properly, I am able to log in , log out , share , invite bla bla bla... But , the problem is that when I log in I grant the user access token and permission , isn't it? Suppose now the user logged out and then want to sign in with same account  here is the problem it gives Login error:....
This is because the user accepted the permissions and bla bla ... 
The question is how to avoid it ? How to let user login automatically if he/she granted permissions ? Thanks in advance :) ...
 @andyborrell

**Comment by youminkim** [comment]
Hi @Chisha14 , If you mean login confirmation screen ( when you try logging in to the app which you already logged in before), it is not error and proper steps to grant access token. Please re-open if you have others. (and please give us the error log or screen)
