### ISSUE TITLE
Unity Facebook SDk how to store players data on Facebook

### ISSUE THREAD

**Issue by maidamedia** [fbsamples/friendsmash-unity#5]
I am using the unity SDK for a game. I followed the FriendSmah tutorial and I replicated everything in my game correctly. In the mentioned demo players data such number of coins, bombs and hearts are always reset to their default standards everytime you enter the game. I would like instead to store those values somewhere on the server, especially if a player buys a game item, he should have to find that item when he will enter the game again. Do I have to create a Data Base structure on my web site or is it possible to use something on Facebook side? Thanks

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by cmlewis89** [comment]
Thank you for the feedback, we are always looking to improve the sample project and adding these features will come in time.
