### ISSUE TITLE
Store and advanced requests!

### ISSUE THREAD

**Issue by edSantos** [fbsamples/friendsmash-unity#6]
Hello!

When will be available more examples about advanced requests (gifting, differentiated requests like ammo and lives and exchange of game goods between friends) and handling purchases on unity. Thanks in advance

Ed

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by cmlewis89** [comment]
Thank you for the feedback, we are always looking to improve the sample project and adding these features will come in time.
